"""Regenerate checked-in conversion SPIR-V headers with Vulkan SDK glslc."""
import argparse
from pathlib import Path
import struct
import subprocess
import tempfile

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--glslc', default='glslc')
    parser.add_argument('only', nargs='*', help='headers to regenerate (default: all)')
    args = parser.parse_args()
    root = Path(__file__).resolve().parent
    for source, header, symbol, defines in [('convert.vert', 'convert_vert_spv.h', 'CONVERT_VERT_SPV', []),
                                    ('convert.frag', 'convert_frag_spv.h', 'CONVERT_FRAG_SPV', []),
                                    ('ycbcr_to_rgba.comp', 'ycbcr_to_rgba_spv.h', 'YCBCR_TO_RGBA_SPV', []),
                                    ('fuse_color.frag', 'fuse_color_frag_spv.h', 'FUSE_COLOR_FRAG_SPV', ['-DFP16=0']),
                                    ('fuse_color.frag', 'fuse_color_fp16_frag_spv.h', 'FUSE_COLOR_FP16_FRAG_SPV', ['-DFP16=1'])]:
        if args.only and header not in args.only:
            continue
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / 'shader.spv'
            subprocess.run([args.glslc, '-O', '--target-env=vulkan1.1', *defines, str(root/source), '-o', str(out)], check=True)
            data = out.read_bytes(); words = struct.unpack(f'<{len(data)//4}I', data)
        lines = [', '.join(f'0x{w:08x}u' for w in words[i:i+8]) for i in range(0, len(words), 8)]
        (root/header).write_text('// Generated by compile_shaders.py; edit the GLSL source.\n#pragma once\n#include <cstdint>\n'
            f'static const uint32_t {symbol}[] = {{\n    ' + ',\n    '.join(lines) + '\n};\n', newline='\n')

if __name__ == '__main__':
    main()
